/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HackathonsNewRouteImport } from './routes/hackathons/new'
import { Route as HackathonsIdIndexRouteImport } from './routes/hackathons/$id/index'
import { Route as HackathonsIdAnalyzingRouteImport } from './routes/hackathons/$id/analyzing'
import { Route as HackathonsIdSettingsRouteImport } from './routes/hackathons/$id/settings'
import { Route as HackathonsIdSubmissionsSubmissionIdRouteImport } from './routes/hackathons/$id/submissions/$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsNewRoute = HackathonsNewRouteImport.update({
  id: '/hackathons/new',
  path: '/hackathons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIdIndexRoute = HackathonsIdIndexRouteImport.update({
  id: '/hackathons/$id/',
  path: '/hackathons/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIdAnalyzingRoute = HackathonsIdAnalyzingRouteImport.update({
  id: '/hackathons/$id/analyzing',
  path: '/hackathons/$id/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIdSettingsRoute = HackathonsIdSettingsRouteImport.update({
  id: '/hackathons/$id/settings',
  path: '/hackathons/$id/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIdSubmissionsSubmissionIdRoute =
  HackathonsIdSubmissionsSubmissionIdRouteImport.update({
    id: '/hackathons/$id/submissions/$submissionId',
    path: '/hackathons/$id/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hackathons/new': typeof HackathonsNewRoute
  '/hackathons/$id/analyzing': typeof HackathonsIdAnalyzingRoute
  '/hackathons/$id/settings': typeof HackathonsIdSettingsRoute
  '/hackathons/$id/': typeof HackathonsIdIndexRoute
  '/hackathons/$id/submissions/$submissionId': typeof HackathonsIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hackathons/new': typeof HackathonsNewRoute
  '/hackathons/$id/analyzing': typeof HackathonsIdAnalyzingRoute
  '/hackathons/$id/settings': typeof HackathonsIdSettingsRoute
  '/hackathons/$id': typeof HackathonsIdIndexRoute
  '/hackathons/$id/submissions/$submissionId': typeof HackathonsIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hackathons/new': typeof HackathonsNewRoute
  '/hackathons/$id/analyzing': typeof HackathonsIdAnalyzingRoute
  '/hackathons/$id/settings': typeof HackathonsIdSettingsRoute
  '/hackathons/$id/': typeof HackathonsIdIndexRoute
  '/hackathons/$id/submissions/$submissionId': typeof HackathonsIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hackathons/new'
    | '/hackathons/$id/analyzing'
    | '/hackathons/$id/settings'
    | '/hackathons/$id/'
    | '/hackathons/$id/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hackathons/new'
    | '/hackathons/$id/analyzing'
    | '/hackathons/$id/settings'
    | '/hackathons/$id'
    | '/hackathons/$id/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/hackathons/new'
    | '/hackathons/$id/analyzing'
    | '/hackathons/$id/settings'
    | '/hackathons/$id/'
    | '/hackathons/$id/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HackathonsNewRoute: typeof HackathonsNewRoute
  HackathonsIdAnalyzingRoute: typeof HackathonsIdAnalyzingRoute
  HackathonsIdSettingsRoute: typeof HackathonsIdSettingsRoute
  HackathonsIdIndexRoute: typeof HackathonsIdIndexRoute
  HackathonsIdSubmissionsSubmissionIdRoute: typeof HackathonsIdSubmissionsSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/new': {
      id: '/hackathons/new'
      path: '/hackathons/new'
      fullPath: '/hackathons/new'
      preLoaderRoute: typeof HackathonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$id/': {
      id: '/hackathons/$id/'
      path: '/hackathons/$id'
      fullPath: '/hackathons/$id/'
      preLoaderRoute: typeof HackathonsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$id/analyzing': {
      id: '/hackathons/$id/analyzing'
      path: '/hackathons/$id/analyzing'
      fullPath: '/hackathons/$id/analyzing'
      preLoaderRoute: typeof HackathonsIdAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$id/settings': {
      id: '/hackathons/$id/settings'
      path: '/hackathons/$id/settings'
      fullPath: '/hackathons/$id/settings'
      preLoaderRoute: typeof HackathonsIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$id/submissions/$submissionId': {
      id: '/hackathons/$id/submissions/$submissionId'
      path: '/hackathons/$id/submissions/$submissionId'
      fullPath: '/hackathons/$id/submissions/$submissionId'
      preLoaderRoute: typeof HackathonsIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HackathonsNewRoute: HackathonsNewRoute,
  HackathonsIdAnalyzingRoute: HackathonsIdAnalyzingRoute,
  HackathonsIdSettingsRoute: HackathonsIdSettingsRoute,
  HackathonsIdIndexRoute: HackathonsIdIndexRoute,
  HackathonsIdSubmissionsSubmissionIdRoute:
    HackathonsIdSubmissionsSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
